title: yw-combat
description: Technical documentation for the YW2 Battle system
url: "https://n123git.github.io"
baseurl: "/yw-combat"

remote_theme: pmarsceill/just-the-docs
dark_mode: true
dark_mode_default: true

# Just-the-Docs options
search_enabled: true
aux_links:
  "Yo-gon Discord": https://discord.gg/dTmEhDVcPQ
